export const emojiCategories = [
  {
    id: 'smileys',
    name: 'Smileys & Emotion',
    emojis: [
      { char: '😀', name: 'grinning face happy smile laugh' },
      { char: '😃', name: 'grinning face big eyes happy smile laugh' },
      { char: '😄', name: 'grinning face smiling eyes happy smile laugh' },
      { char: '😁', name: 'beaming face smiling eyes happy grin' },
      { char: '😆', name: 'grinning squinting face happy laugh' },
      { char: '😅', name: 'grinning face with sweat hot relief' },
      { char: '😂', name: 'face with tears of joy laugh crying lol' },
      { char: '🤣', name: 'rolling on the floor laughing rofl laugh lol' },
      { char: '😊', name: 'smiling face happy smile blush' },
      { char: '😇', name: 'smiling face with halo angel innocent' },
      { char: '🙂', name: 'slightly smiling face smile' },
      { char: '🙃', name: 'upside-down face silly' },
      { char: '😉', name: 'winking face wink' },
      { char: '😌', name: 'relieved face calm' },
      { char: '😍', name: 'smiling face with heart-eyes love heart adore' },
      { char: '🥰', name: 'smiling face with hearts love happy adore' },
      { char: '😘', name: 'face blowing a kiss love kiss' },
      { char: '😋', name: 'face savoring food delicious yum' },
      { char: '😛', name: 'face with tongue silly' },
      { char: '😜', name: 'winking face with tongue silly wink' },
      { char: '🤪', name: 'zany face crazy wild silly' },
      { char: '🤨', name: 'face with raised eyebrow suspicious' },
      { char: '🧐', name: 'face with monocle smart posh' },
      { char: '🤓', name: 'nerd face smart geek' },
      { char: '😎', name: 'smiling face with sunglasses cool sunglasses' },
      { char: '🥳', name: 'partying face celebrate congratulations' },
      { char: '😏', name: 'smirking face sly smirk' },
      { char: '😒', name: 'unamused face meh bored' },
      { char: '😞', name: 'disappointed face sad' },
      { char: '😔', name: 'pensive face sad' },
      { char: '🥺', name: 'pleading face puppy eyes sad' },
      { char: '😢', name: 'crying face sad tear' },
      { char: '😭', name: 'loudly crying face sad tears cry sob' },
      { char: '😤', name: 'face with steam from nose angry' },
      { char: '😠', name: 'angry face mad' },
      { char: '😡', name: 'enraged face angry mad' },
      { char: '🤯', name: 'exploding head mind blown shock' },
      { char: '😳', name: 'flushed face embarrassed shock' },
      { char: '🥵', name: 'hot face red heat sweat' },
      { char: '🥶', name: 'cold face blue freezing ice' },
      { char: '😱', name: 'face screaming in fear scared shock' },
      { char: '🤔', name: 'thinking face hmm wonder puzzle' }
    ]
  },
  {
    id: 'people',
    name: 'People & Body',
    emojis: [
      { char: '👋', name: 'waving hand wave hello goodbye' },
      { char: '🤚', name: 'raised back of hand' },
      { char: '✋', name: 'raised hand stop' },
      { char: '🖖', name: 'vulcan salute spock live long prosper' },
      { char: '👌', name: 'ok hand okay correct good' },
      { char: '🤌', name: 'pinched fingers italian what' },
      { char: '🤏', name: 'pinching hand small little' },
      { char: '✌️', name: 'victory hand peace win' },
      { char: '🤞', name: 'crossed fingers hope luck' },
      { char: '🫰', name: 'hand with crossed index and thumb heart love' },
      { char: '🤟', name: 'love-you gesture sign love' },
      { char: '🤘', name: 'sign of the horns rock metal' },
      { char: '🤙', name: 'call me hand phone' },
      { char: '👍', name: 'thumbs up like approve yes' },
      { char: '👎', name: 'thumbs down dislike disapprove no' },
      { char: '✊', name: 'raised fist solidarity power' },
      { char: '👊', name: 'oncoming fist punch hit' },
      { char: '👏', name: 'clapping hands clap congrats' },
      { char: '🙌', name: 'raising hands celebrate cheer' },
      { char: '👐', name: 'open hands' },
      { char: '🤲', name: 'palms up together' },
      { char: '🤝', name: 'handshake deal agreement partner' },
      { char: '🙏', name: 'folded hands pray please thank you' },
      { char: '✍️', name: 'writing hand write' },
      { char: '💅', name: 'nail polish sassy cosmetic' },
      { char: '🤳', name: 'selfie camera phone' },
      { char: '💪', name: 'flexed biceps strong muscle power' },
      { char: '👂', name: 'ear listen hear' },
      { char: 'nose', name: 'nose smell' },
      { char: '🧠', name: 'brain smart think mind' },
      { char: '👀', name: 'eyes look watch see' }
    ]
  },
  {
    id: 'animals',
    name: 'Animals & Nature',
    emojis: [
      { char: '🐶', name: 'dog puppy pet animal' },
      { char: '🐱', name: 'cat kitten pet animal' },
      { char: '🐭', name: 'mouse rodent animal' },
      { char: '🐹', name: 'hamster rodent animal' },
      { char: '🐰', name: 'rabbit bunny animal' },
      { char: '🦊', name: 'fox animal wild' },
      { char: '🐻', name: 'bear wild animal' },
      { char: '🐼', name: 'panda animal cute' },
      { char: '🐨', name: 'koala animal cute' },
      { char: '🐯', name: 'tiger wild animal cat' },
      { char: '🦁', name: 'lion wild animal cat king' },
      { char: '🐮', name: 'cow farm animal' },
      { char: '🐷', name: 'pig farm animal' },
      { char: '🐸', name: 'frog amphibian animal' },
      { char: '🐵', name: 'monkey face animal' },
      { char: '🐔', name: 'chicken farm animal bird' },
      { char: '🐧', name: 'penguin bird animal cold' },
      { char: '🐦', name: 'bird animal fly' },
      { char: '🐤', name: 'baby chick bird' },
      { char: '🦆', name: 'duck bird animal' },
      { char: '🦅', name: 'eagle bird wild' },
      { char: '🦉', name: 'owl bird smart' },
      { char: '🦄', name: 'unicorn magic horse' },
      { char: '🐝', name: 'honeybee bee insect' },
      { char: '🐛', name: 'bug caterpillar insect' },
      { char: '🦋', name: 'butterfly insect pretty' },
      { char: '🐙', name: 'octopus sea animal fish' },
      { char: '🐬', name: 'dolphin sea animal mammal' },
      { char: '🐳', name: 'spouting whale sea animal' },
      { char: '🦈', name: 'shark sea animal fish' }
    ]
  },
  {
    id: 'food',
    name: 'Food & Drink',
    emojis: [
      { char: '🍎', name: 'red apple fruit' },
      { char: '🍌', name: 'banana fruit yellow' },
      { char: '🍉', name: 'watermelon fruit summer' },
      { char: '🍇', name: 'grapes fruit' },
      { char: '🍓', name: 'strawberry fruit sweet' },
      { char: '🫐', name: 'blueberries fruit' },
      { char: '🍋', name: 'lemon fruit sour' },
      { char: '🥑', name: 'avocado vegetable green healthy' },
      { char: '🥕', name: 'carrot vegetable healthy' },
      { char: '🌽', name: 'ear of corn vegetable' },
      { char: '🍞', name: 'bread bakery toast' },
      { char: '🥐', name: 'croissant bakery bread' },
      { char: 'Cheese', name: 'cheese block' },
      { char: '🍳', name: 'cooking egg breakfast pan' },
      { char: '🥓', name: 'bacon meat pork breakfast' },
      { char: '🍔', name: 'hamburger burger fast food' },
      { char: '🍟', name: 'french fries chips fast food' },
      { char: '🍕', name: 'pizza cheese fast food Italian' },
      { char: '🌭', name: 'hot dog fast food sausage' },
      { char: '🌮', name: 'taco mexican food' },
      { char: '🌯', name: 'burrito mexican food' },
      { char: '🍜', name: 'steaming bowl ramen noodles pasta asian' },
      { char: '🍣', name: 'sushi japanese asian fish' },
      { char: '🍰', name: 'shortcake cake sweet dessert' },
      { char: '🧁', name: 'cupcake sweet dessert bakery' },
      { char: '🍫', name: 'chocolate bar sweet candy' },
      { char: '🍿', name: 'popcorn snack movie' },
      { char: '☕', name: 'hot beverage coffee tea cafe warm' },
      { char: '🍵', name: 'teacup without handle green tea asian' },
      { char: '🍺', name: 'beer mug alcohol drink pint' },
      { char: '🍻', name: 'clinking beer mugs drink alcohol cheers toast' },
      { char: '🍷', name: 'wine glass alcohol drink' }
    ]
  },
  {
    id: 'travel',
    name: 'Travel & Places',
    emojis: [
      { char: '🚗', name: 'automobile car vehicle' },
      { char: '🚕', name: 'taxi cab vehicle' },
      { char: '🚌', name: 'bus vehicle transport' },
      { char: '🚓', name: 'police car vehicle cop patrol' },
      { char: '🚑', name: 'ambulance vehicle hospital emergency' },
      { char: '🚒', name: 'fire engine truck vehicle emergency' },
      { char: '🚲', name: 'bicycle bike transport ride' },
      { char: '🛵', name: 'motor scooter vehicle vespa' },
      { char: '✈️', name: 'airplane plane travel flight fly' },
      { char: '🚀', name: 'rocket fast space launch ship' },
      { char: '🛸', name: 'ufo spaceship alien space' },
      { char: '🪐', name: 'ringed planet saturn space' },
      { char: '🌠', name: 'shooting star space sky' },
      { char: '🌃', name: 'night with stars city' },
      { char: '🏙️', name: 'cityscape city skyline buildings' },
      { char: '🌄', name: 'sunrise over mountains' },
      { char: '🌅', name: 'sunrise sun morning' },
      { char: '🌈', name: 'rainbow pretty colorful weather' },
      { char: '🌋', name: 'volcano mountain hot nature' },
      { char: '🏔️', name: 'snow-capped mountain cold peak' },
      { char: '⛺', name: 'tent camp camp nature' },
      { char: '🏖️', name: 'beach with umbrella summer vacation' },
      { char: '🏝️', name: 'desert island tropical beach' },
      { char: '🏢', name: 'office building workspace work' }
    ]
  },
  {
    id: 'activities',
    name: 'Activities',
    emojis: [
      { char: '⚽', name: 'soccer ball football sport play' },
      { char: '篮球', name: 'basketball ball sport play' },
      { char: '🏈', name: 'american football sport ball' },
      { char: '⚾', name: 'baseball ball sport' },
      { char: '🎾', name: 'tennis ball sport' },
      { char: '🏐', name: 'volleyball ball sport' },
      { char: '🏉', name: 'rugby football sport ball' },
      { char: '🎱', name: 'pool 8ball billiards game sport' },
      { char: '🎯', name: 'bullseye dart direct target game' },
      { char: '🎮', name: 'video game controller console gamer' },
      { char: '🏆', name: 'trophy prize winner award success' },
      { char: '🥇', name: '1st place medal gold winner' },
      { char: '🥈', name: '2nd place medal silver' },
      { char: '🥉', name: '3rd place medal bronze' },
      { char: '🎨', name: 'artist palette paint art creative' },
      { char: '🎬', name: 'clapper board movie film director' },
      { char: '🎤', name: 'microphone sing music audio' },
      { char: '🎧', name: 'headphone music audio listen' },
      { char: '🎸', name: 'guitar instrument music' },
      { char: '🎹', name: 'musical keyboard piano instrument' },
      { char: '♟️', name: 'chess pawn game board' },
      { char: '🎳', name: 'bowling sport game' }
    ]
  },
  {
    id: 'objects',
    name: 'Objects',
    emojis: [
      { char: '💻', name: 'laptop computer tech coding code work' },
      { char: '⌨️', name: 'keyboard computer input coding' },
      { char: '📱', name: 'mobile phone cell tech call' },
      { char: '🖥️', name: 'desktop computer screen monitor' },
      { char: '🖨️', name: 'printer paper office' },
      { char: '💡', name: 'light bulb idea creative smart brightness' },
      { char: '🔦', name: 'flashlight light dark night' },
      { char: '📚', name: 'books read study library' },
      { char: '💰', name: 'money bag cash coin rich wealth' },
      { char: '💵', name: 'dollar banknote money cash' },
      { char: '✉️', name: 'envelope mail letter post' },
      { char: '📦', name: 'package box delivery mail' },
      { char: '✏️', name: 'pencil write draw office' },
      { char: '🔒', name: 'locked lock secure private' },
      { char: '🔓', name: 'unlocked lock open security' },
      { char: '🔑', name: 'key open password security' },
      { char: '🔨', name: 'hammer tool build repair' },
      { char: '⚙️', name: 'gear settings setup control' },
      { char: '🔫', name: 'water pistol gun weapon' },
      { char: '💣', name: 'bomb explode danger' },
      { char: '🎈', name: 'balloon party celebrate' },
      { char: '🎁', name: 'wrapped gift present birthday surprise' }
    ]
  },
  {
    id: 'symbols',
    name: 'Symbols',
    emojis: [
      { char: '❤️', name: 'red heart love passion like' },
      { char: '🧡', name: 'orange heart love' },
      { char: '💛', name: 'yellow heart love' },
      { char: '💚', name: 'green heart love' },
      { char: '💙', name: 'blue heart love' },
      { char: '💜', name: 'purple heart love' },
      { char: '🖤', name: 'black heart love' },
      { char: '🤍', name: 'white heart love' },
      { char: '💖', name: 'sparkling heart love pretty' },
      { char: '💔', name: 'broken heart sad love' },
      { char: '💯', name: 'hundred percent perfect absolute correct' },
      { char: '💬', name: 'speech balloon chat comment message text' },
      { char: '💭', name: 'thought balloon think dream' },
      { char: '⚠️', name: 'warning danger caution alert' },
      { char: '🛑', name: 'stop sign red' },
      { char: '🚫', name: 'prohibited forbidden stop no' },
      { char: '✅', name: 'white heavy check mark green yes correct ok' },
      { char: '❌', name: 'cross mark red no wrong cancel' },
      { char: '➕', name: 'plus add math' },
      { char: '➖', name: 'minus subtract math' },
      { char: '❓', name: 'question mark help wonder' },
      { char: '❔', name: 'white question mark help' },
      { char: '🔔', name: 'bell notification alert sound' },
      { char: '🔕', name: 'bell with slash silent mute sound' },
      { char: '🌀', name: 'cyclone storm weather spinner' }
    ]
  },
  {
    id: 'flags',
    name: 'Flags',
    emojis: [
      { char: '🏁', name: 'chequered flag finish race' },
      { char: '🚩', name: 'triangular flag post marker sign' },
      { char: '🎌', name: 'crossed flags japan' },
      { char: '🏴‍☠️', name: 'pirate flag skull bones' },
      { char: '🏳️‍🌈', name: 'rainbow flag pride lgbt lgbtq' },
      { char: '🏳️‍⚧️', name: 'transgender flag pride trans' },
      { char: '🇺🇸', name: 'us flag united states america' },
      { char: '🇬🇧', name: 'uk flag united kingdom britain england' },
      { char: '🇮🇳', name: 'india flag indian' },
      { char: '🇨🇦', name: 'canada flag canadian' },
      { char: '🇩🇪', name: 'germany flag german' },
      { char: '🇫🇷', name: 'france flag french' },
      { char: '🇯🇵', name: 'japan flag japanese' },
      { char: '🇨🇳', name: 'china flag chinese' },
      { char: '🇪🇺', name: 'european union flag eu' },
      { char: '🇧🇷', name: 'brazil flag brazilian' },
      { char: '🇦🇺', name: 'australia flag australian' }
    ]
  }
];

export const searchEmojis = (query) => {
  if (!query) return [];
  const cleanQuery = query.toLowerCase().trim();
  const results = [];
  
  for (const cat of emojiCategories) {
    for (const emoji of cat.emojis) {
      if (emoji.name.includes(cleanQuery)) {
        results.push(emoji);
      }
    }
  }
  return results;
};
